general.import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
#family = "MesloLGS Nerd Font Mono"
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
# family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font"
# family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
#  family = "MesloLGS Nerd Font Mono"
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[keyboard]
bindings = [
  { key = "ArrowLeft", mods = "Control", chars = "\u001bb" },
  { key = "ArrowRight", mods = "Control", chars = "\u001bf" },
  { key = "ArrowLeft", mods = "Control|Shift", action = "First" },
  { key = "ArrowRight", mods = "Control|Shift", action = "Last" }
]
