#!/bin/sh

# Определяем цвета
# Определяем цвета
BLANK='#282828' 
CLEAR='#ebdbb2' 
DEFAULT='#83a598' 
TEXT='#ebdbb2' 
WRONG='#d3869b' 
VERIFYING='#8ec07c' 

# Запускаем i3lock с заданными цветами
i3lock \
--insidever-color=$BLANK \
--ringver-color=$VERIFYING \
\
--insidewrong-color=$BLANK \
--ringwrong-color=$WRONG \
\
--inside-color=$BLANK \
--ring-color=$DEFAULT \
--line-color=$BLANK \
--separator-color=$DEFAULT \
\
--verif-color=$TEXT \
--wrong-color=$TEXT \
--time-color=$TEXT \
--date-color=$TEXT \
--layout-color=$TEXT \
--keyhl-color=$WRONG \
--bshl-color=$WRONG \
\
--screen 1 \
--blur 9 \
--clock \
--indicator \
--time-str="%H:%M" \
--date-str="%A, %Y-%m-%d"
